# Generated by Django 4.2.30 on 2026-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, help_text='Önceki mesajların yapay zeka tarafından oluşturulmuş özeti', null=True),
        ),
    ]
