# Generated by Django 4.2.30 on 2026-07-02 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='global_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Doküman',
                'verbose_name_plural': 'Global Dokümanlar',
                'ordering': ['created_at'],
            },
        ),
    ]
