# Generated by Django 4.2.30 on 2026-07-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_globaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='GlobalDocument',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
